Updated Specification and Documentation to support Audio Modality.
modelcontextprotocol/specification pull request #93
Opened 2024-12-01 12:09 UTC by evalstate

This change supports discussion #88 and includes Audio Modality in the specification. 

## Motivation and Context
This would enable integration with models that support Audio as input/output in context such as `gpt-4o-audio-preview`. 
https://platform.openai.com/docs/guides/audio

## How Has This Been Tested?

This has been tested using the Inspector tool, with local type extensions:

```typescript
// Define the AudioContent schema
export const AudioContentSchema = z.object({
  type: z.literal("audio"),
  data: z.string().base64(),
  mimeType: z.string(),
}).passthrough();

// Extend the CallToolResult schema to include audio content
export const ExtendedCallToolResultSchema = ResultSchema.extend({
  content: z.array(
    z.discriminatedUnion("type", [
      TextContentSchema,
      ImageContentSchema,
      AudioContentSchema,
      EmbeddedResourceSchema,
    ])
  ),
  isError: z.boolean().default(false).optional(),
});

// Export the types
export type AudioContent = z.infer<typeof AudioContentSchema>;
export type ExtendedCallToolResult = z.infer<typeof ExtendedCallToolResultSchema>;
```

The Inspector application was updated to render the Audio player for this type:

```typescript
              {item.type === "image" && (
                <img
                  src={`data:${item.mimeType};base64,${item.data}`}
                  ...
              {item.type === "audio" && (
                  <audio
                  controls
                  src={`data:${item.mimeType};base64,${item.data}`}
```

![image](https://github.com/user-attachments/assets/f96857f6-c29b-49f4-bb35-3b7507704798)

The Server produced this JSON:

```
      const audioBase64 = await generateSpeech(text);
      return {
        content: [{
          type: "audio",
            mimeType: "audio/wav",
            data: audioBase64
        }]
      };
    }
```

I was unable to find the process to build the TypeScript SDK from the Schema, hence the approach of extending types.

Ultimately I would like to integrate this in to my Chat application supporting gpt-4o (and potential new models) with Audio support.

## Breaking Changes

No. However:
1) The Client Reference Implementation (Claude Desktop) does not support audio.
2) The SDKs will require updating to include the extended type.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] Documentation update

## Checklist

- [X] I have read the [MCP Documentation](https://modelcontextprotocol.io)
- [X] My code follows the repository's style guidelines
- [X] New and existing tests pass locally
- [X] I have added appropriate error handling
- [X] I have added or updated documentation as needed

## Additional context

I believe that adding the "Audio" type is appropriate as it seems congruent the way that text/image modalities are typically handled.

```typescript
modalities: ["text", "audio"],
```

2024-12-02 13:11 UTC, jspahrsummers submitted a review, later dismissed
Thank you! This makes sense to me, and seems like a clean extension to the protocol.

@dsp-ant Any thoughts?

2024-12-02 13:11 UTC, jspahrsummers commented on docs/specification/client/sampling.md
> +The Model Context Protocol (MCP) provides a standardized way for servers to request LLM sampling ("completions" or "generations") from language models via clients. This flow allows clients to maintai
```suggestion
The Model Context Protocol (MCP) provides a standardized way for servers to request LLM sampling ("completions" or "generations") from language models via clients. This flow allows clients to maintain control over model access, selection, and permissions while enabling servers to leverage AI capabilities&mdash;with no server API keys necessary. Servers can request text, audio, or image-based interactions and optionally include context from MCP servers in their prompts.
```

2024-12-02 13:24 UTC, jspahrsummers commented
We _might_ want to rev the protocol version, since this would be a new `type` that receivers may not be expecting.

2024-12-02 16:12 UTC, dsp-ant commented
This seems reasonable to me. I am not accepting mostly so we don't accidentally merge this. We need to first rev the protocol and add ways to handle revisions in the current protocol.

2024-12-02 17:55 UTC, evalstate commented
> This seems reasonable to me. I am not accepting mostly so we don't accidentally merge this. We need to first rev the protocol and add ways to handle revisions in the current protocol.

@dsp-ant - I couldn't find the tool/script to generate new versions of the SDKs from the spec for testing - are they available?

2025-01-10 10:44 UTC, jspahrsummers commented
We've now created a separate place for the draft version of the spec. Can you please move this there?

> I couldn't find the tool/script to generate new versions of the SDKs from the spec for testing - are they available?

We use Claude to update the SDKs in response to spec changes—e.g., by giving it the current SDK interfaces and a diff of what changed in the schema.

2025-01-15 08:57 UTC, evalstate commented
As requested, updated to point changes to draft version of spec.

@dsp-ant - i decided to create `/schema/draft/schema.ts` for the changes. the validate and build scripts have been updated to handle both main and draft schemas.

2025-01-15 10:53 UTC, jspahrsummers requested changes
Thanks for doing this! I left a couple of comments on the doc page which should be fixed, but then also a couple of questions for @dsp-ant about how we want to do versioning—he's been leading the charge on the release vs. draft spec 🙂

2025-01-15 10:53 UTC, jspahrsummers commented on docs/specification/draft/client/sampling.md
> +Clients that support sampling **MUST** declare the `sampling` capability during [initialization]({{< ref "/specification/2024-11-05/basic/lifecycle#initialization" >}}):
Why the change to this link?

2025-01-15 10:53 UTC, jspahrsummers commented on docs/specification/draft/client/sampling.md
> +**Protocol Revision**: {{< param protocolRevision >}}
I think we want this page to always say "draft," rather than a specific date, to indicate that it's not codified yet.

2025-01-15 10:53 UTC, jspahrsummers commented on schema/draft/schema.ts
> +/* JSON-RPC types */
@dsp-ant I wonder if we should have a separate schema.ts for each version (in folders named accordingly)

2025-01-15 10:53 UTC, jspahrsummers commented on schema/draft/schema.ts
> +export const LATEST_PROTOCOL_VERSION = "2024-11-05";
@dsp-ant What do you want to go here while the schema is in draft?

2025-01-15 11:11 UTC, evalstate commented on schema/draft/schema.ts
> +export const LATEST_PROTOCOL_VERSION = "2024-11-05";
Adding context from the conversation yesterday: 

![image](https://github.com/user-attachments/assets/dfa11aa9-a835-4ed6-bbb0-d69fec30596f)

2025-01-15 11:14 UTC, dsp-ant commented on schema/draft/schema.ts
> +/* JSON-RPC types */
Yes we should. Let's accept this PR and then mover the existing schema in another PR to `schema/2024-11-05/schema.ts`

2025-01-15 11:23 UTC, dsp-ant commented on schema/draft/schema.ts
> +export const LATEST_PROTOCOL_VERSION = "2024-11-05";
LATEST_PROTOCOL_VERSION should be `DRAFT-<YEAR>-<SOME_NAME>-<GENERATION>` in order to distinguish draft names. Happy to figure out waht the naming scheme is, but I would say this one could be `DRAFT-2025-ALAN-01` and we bump generation everytime we update the draft spec with a new thing. The name between date and generation is to ensure people dont read it as a month. Thoughts?

2025-01-15 11:29 UTC, dsp-ant commented on schema/draft/schema.ts
> +export const LATEST_PROTOCOL_VERSION = "2024-11-05";
Claude says we should fix the number format, so it would be `DRAFT-2025-ALAN-0001`

2025-01-15 11:37 UTC, evalstate commented
I've updated the link in the client/sampling.md to be a relative link - should make maintaining draft/versions easier?

2025-01-15 11:38 UTC, evalstate reviewed
Updated link to be relative - should make moving between versions easier.

2025-01-15 13:12 UTC, dsp-ant commented on schema/draft/schema.ts
> +export const LATEST_PROTOCOL_VERSION = "2024-11-05";
`DRAFT-2025-v1` is the choice. First new draft in 2025

2025-01-16 14:07 UTC, evalstate commented on schema/draft/schema.ts
> +export const LATEST_PROTOCOL_VERSION = "2024-11-05";
Updated PR with protocol version `DRAFT-2025-v1` in schema/draft/schema.ts.

2025-01-16 14:11 UTC, evalstate commented on schema/draft/schema.ts
> +/* JSON-RPC types */
Resolving on basis that existing schema will be moved in a separate operation.

2025-01-16 19:39 UTC, dsp-ant approved these changes
I think the nits we can work out later. Happy with that. Thank you.

2025-01-16 19:39 UTC, dsp-ant commented on docs/specification/draft/client/sampling.md
> +**Protocol Revision**: {{< param protocolRevision >}}
I think this still needs to say "draft"

2025-01-16 20:28 UTC, evalstate commented on docs/specification/draft/client/sampling.md
> +**Protocol Revision**: {{< param protocolRevision >}}
my bad, updated!

2025-01-17 09:19 UTC, jspahrsummers approved these changes

2025-01-17 18:44 UTC, dsp-ant approved these changes

2025-01-17 19:29 UTC, merged

2025-04-20 01:23 UTC, gmlewis commented on schema/draft/schema.json
> +            "$ref": "#/definitions/Result"
Note that the `"description"` field for `EmptyResult` is missing here, whereas it is present in `schema.ts` [on line 129.](https://github.com/modelcontextprotocol/modelcontextprotocol/blob/623e37a3542ceaae0defe1a8450598b90ebbfbf2/schema/2025-03-26/schema.ts#L129)

2025-04-20 01:35 UTC, gmlewis reviewed
Here are a couple more conversion errors for those who are relying on `schema.json` to match `schema.ts`.

2025-04-20 01:35 UTC, gmlewis commented on schema/draft/schema.json
> +                    "$ref": "#/definitions/Result"
According to `schema.ts`, this line should say `.../EmptyResult`, not `.../Result`.

2025-04-20 01:35 UTC, gmlewis commented on schema/draft/schema.json
> +                    "$ref": "#/definitions/Result"
According to `schema.ts`, this line should say `.../EmptyResult`, not `.../Result`.